#!/bin/bash
xrandr  --output eDP1 --rotate inverted


dev1=$(xsetwacom --list devices | cut -f2  | cut -f2 -d' ' | head -1)
dev2=$(xsetwacom --list devices | cut -f2  | cut -f2 -d' ' | head -2| tail -1)
dev3=$(xsetwacom --list devices | cut -f2  | cut -f2 -d' ' | tail -1)
echo $dev1
xsetwacom  set "$dev1" Rotate half
xsetwacom  set "$dev2" Rotate half
xsetwacom  set "$dev3" Rotate half

start
